name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Typecheck, Test, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dagger/dagger-for-github@v8.4.0
        with:
          verb: call
          args: ci --source=.
          version: "0.18.12"
