name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: dagger/dagger-for-github@v8.4.0
        with:
          verb: call
          args: publish --source=. --tag=${{ github.event.release.tag_name }} --registry-token=env:GITHUB_TOKEN
          version: "latest"
